# Generated by Django 4.2.5 on 2023-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdx_auth", "0002_alter_pdxuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdxuser",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
