# Generated by Django 4.2.5 on 2024-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdx_auth', '0003_pdxuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdxuser',
            name='otp_generated_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
