# Generated by Django 4.2.5 on 2024-02-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdx_auth', '0004_connectedapplication'),
        ('pdx_auth', '0004_pdxuser_otp_generated_at'),
    ]

    operations = [
    ]
